"use client";
import { useEffect, useMemo, useState } from "react";
import { withBasePath } from "@/lib/base-path.ts";

type KitFile = { path: string; content: string | null };
type Tool = "claude" | "opencode";

const TOOL_ROOT: Record<Tool, string> = { claude: ".claude/", opencode: "opencode/" };
const TOOL_LABEL: Record<Tool, string> = { claude: "Claude Code", opencode: "OpenCode" };

function dirOf(path: string): string {
  const i = path.lastIndexOf("/");
  return i === -1 ? "" : path.slice(0, i);
}

function baseOf(path: string): string {
  return path.slice(path.lastIndexOf("/") + 1);
}

/**
 * A starter kit's real files, fetched on demand.
 *
 * The payload is generated by scripts/build-starters.mjs rather than inlined into
 * the pattern page: 24 kits of source would be dead weight in every prerendered
 * HTML file, and the reader only ever opens one.
 *
 * Kits that ship both halves — a `.claude/` tree and an `opencode/` tree — get a
 * switcher that scopes the tool-specific subtree. The kit's shared files stay
 * visible either way, because README.md and PATTERN.md belong to both.
 */
export function StarterViewer({
  slug,
  repo,
  commit,
}: {
  slug: string;
  repo: string;
  commit: string;
}) {
  // One state object tagged with the slug it describes, set only from the fetch's
  // async callbacks. Clearing it synchronously at the top of the effect would be
  // the `react-hooks/set-state-in-effect` error Loop 2 repaired as R2; comparing
  // `loaded.slug` to the prop gives the same "show loading again" behaviour with
  // no setState in the effect body at all.
  const [loaded, setLoaded] = useState<{
    slug: string;
    files: KitFile[] | null;
    error: string | null;
  } | null>(null);
  const [tool, setTool] = useState<Tool>("claude");
  const [picked, setPicked] = useState<string | null>(null);

  useEffect(() => {
    let live = true;
    fetch(withBasePath(`/starters/${slug}.json`))
      .then((r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return r.json() as Promise<{ files: KitFile[] }>;
      })
      .then((data) => {
        if (live) setLoaded({ slug, files: data.files, error: null });
      })
      .catch((e: unknown) => {
        if (live) {
          setLoaded({
            slug,
            files: null,
            error: e instanceof Error ? e.message : "unknown error",
          });
        }
      });
    return () => {
      live = false;
    };
  }, [slug]);

  const fresh = loaded?.slug === slug ? loaded : null;
  const files = fresh?.files ?? null;
  const error = fresh?.error ?? null;

  const hasClaude = !!files?.some((f) => f.path.startsWith(TOOL_ROOT.claude));
  const hasOpencode = !!files?.some((f) => f.path.startsWith(TOOL_ROOT.opencode));
  const bothTools = hasClaude && hasOpencode;

  const visible = useMemo(() => {
    if (!files) return [];
    if (!bothTools) return files;
    const hidden = TOOL_ROOT[tool === "claude" ? "opencode" : "claude"];
    return files.filter((f) => !f.path.startsWith(hidden));
  }, [files, bothTools, tool]);

  // Grouped by directory rather than as a nested tree: kit paths are three levels
  // deep at most, and a flat group list is far easier to operate with a keyboard.
  const groups = useMemo(() => {
    const byDir = new Map<string, KitFile[]>();
    for (const file of visible) {
      const dir = dirOf(file.path);
      const bucket = byDir.get(dir);
      if (bucket) bucket.push(file);
      else byDir.set(dir, [file]);
    }
    return [...byDir].sort(([a], [b]) => a.localeCompare(b));
  }, [visible]);

  // No selection yet, or the switcher just hid the picked file: fall back to the
  // kit's README, which every one of the 24 ships.
  const current =
    visible.find((f) => f.path === picked) ??
    visible.find((f) => f.path === "README.md") ??
    visible[0] ??
    null;
  const selected = current?.path ?? null;

  if (error) {
    return (
      <p className="mono mt-4 border border-rule bg-surface p-4 text-sm text-graphite">
        The starter kit files could not be loaded ({error}). Browse them in the course
        repo instead:{" "}
        <a
          href={`https://github.com/${repo}/tree/${commit}/starters/${slug}`}
          target="_blank"
          rel="noopener noreferrer"
          className="text-accent underline underline-offset-2"
        >
          starters/{slug}
        </a>
        .
      </p>
    );
  }

  if (!files) {
    return (
      <p className="mono mt-4 text-sm text-muted" aria-live="polite">
        Loading the {slug} starter kit…
      </p>
    );
  }

  return (
    <div className="mt-4">
      {bothTools && (
        <fieldset className="border-0 p-0">
          <legend className="mono text-xs uppercase tracking-wider text-muted">
            Harness
          </legend>
          <div className="mt-2 flex gap-2">
            {(["claude", "opencode"] as const).map((t) => (
              <button
                key={t}
                type="button"
                aria-pressed={tool === t}
                onClick={() => setTool(t)}
                className={`mono border px-2 py-1 text-xs ${
                  tool === t
                    ? "border-accent bg-accent text-paper"
                    : "border-rule text-graphite hover:border-accent"
                }`}
              >
                {TOOL_LABEL[t]}
              </button>
            ))}
          </div>
        </fieldset>
      )}

      <div className="mt-4 grid gap-4 border border-rule md:grid-cols-[minmax(0,15rem)_minmax(0,1fr)]">
        <nav
          aria-label={`${slug} starter kit files`}
          className="border-rule p-3 md:border-r"
        >
          <p className="mono text-xs uppercase tracking-wider text-muted">
            {visible.length} files
          </p>
          {groups.map(([dir, entries]) => (
            <details key={dir || "/"} open className="mt-3">
              <summary className="mono cursor-pointer text-xs text-graphite marker:text-rule">
                {dir || "/"}
              </summary>
              <ul className="mt-1">
                {entries.map((file) => (
                  <li key={file.path}>
                    <button
                      type="button"
                      aria-current={selected === file.path ? "true" : undefined}
                      onClick={() => setPicked(file.path)}
                      className={`mono block w-full truncate py-0.5 pl-3 text-left text-xs ${
                        selected === file.path
                          ? "text-accent"
                          : "text-graphite hover:text-accent"
                      }`}
                    >
                      {baseOf(file.path)}
                    </button>
                  </li>
                ))}
              </ul>
            </details>
          ))}
        </nav>

        <div className="min-w-0 p-3">
          {current === null ? (
            <p className="mono text-sm text-muted">Pick a file to read it.</p>
          ) : current.content === null ? (
            <p className="mono text-sm text-graphite">
              Binary or oversized —{" "}
              <a
                href={`https://github.com/${repo}/blob/${commit}/starters/${slug}/${current.path}`}
                target="_blank"
                rel="noopener noreferrer"
                className="text-accent underline underline-offset-2"
              >
                view on GitHub
              </a>
              .
            </p>
          ) : (
            <>
              <p className="mono mb-2 truncate text-xs text-muted">{current.path}</p>
              {/* tabIndex makes the scroll box reachable without a mouse — a file
                  longer than 32rem is otherwise unreadable by keyboard alone.
                  The label names which file, since the region is now a tab stop. */}
              <pre
                tabIndex={0}
                role="region"
                aria-label={`${current.path} contents`}
                className="mono max-h-[32rem] overflow-auto border border-rule bg-paper p-3 text-xs leading-relaxed text-graphite"
              >
                {current.content}
              </pre>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
